### PR TITLE
Add adaptive option to .fitIn() + .trim() support

### PR DESCRIPTION
**Pull request by Slessi**
https://thumbor.readthedocs.io/en/latest/usage.html

```
/hmac/trim/AxB:CxD/(adaptative-)(full-)fit-in/-Ex-F/HALIGN/VALIGN/smart/filters:FILTERNAME(ARGUMENT):FILTERNAME(ARGUMENT)/*IMAGE-URI*
```

> trim removes surrounding space in images using top-left pixel color unless specified otherwise;

>  fit-in means that the generated image should not be auto-cropped and otherwise just fit in an imaginary box specified by ExF. If a full fit-in is specified, then the largest size is used for cropping (width instead of height, or the other way around). If adaptive fit-in is specified, it inverts requested width and height if it would get a better image definition;

### CODE REVIEW

**Comment by codetheweb** [comment]
If I'm understanding the logic correctly, I think it might make more sense to combine `.fitInFlag` + `.fitInType` so the new enum would look something like this:

```ts
export enum FIT_IN_TYPE {
	NONE = 'NONE',
	DEFAULT = 'DEFAULT',
	FULL = 'FULL',
	ADAPTIVE = 'ADAPTIVE'
}
```

(feel free to rename stuff if you come up with something better).

**Comment by Slessi** [comment]
I added `DEFAULT`, but I used `undefined` for the `NONE` case as it would be the default case in the switch anyway and it would be weird to allow a user to add `fitIn(100, 100, FIT_IN_TYPE.NONE)` so would even require some extra type magic like `Exclude<FIT_IN_TYPE, FIT_IN_TYPE.NONE>`

**Comment by codetheweb** [comment]
Ok, makes sense.

Should be good to go after adding a test case. 👍

**Comment by Slessi** [comment]
@codetheweb Added test cases. There was a bug with `DEFAULT_PARAMETERS`, as it was an object used by reference from the `Thumbor` class, changes to it persisted across different `Thumbor` instances. E.g. call set `trimFlag = true` or `smart = true` once and they are `true` forever, as it updated the `DEFAULT_PARAMETERS` object itself.

Changed to a function which creates a new defaults object every time.

**Comment by codetheweb** [comment]
Good catch, thanks.

**Comment by codetheweb** [comment]
Published as v2.0.0 as this includes breaking changes.

**Pull request merged**
